# Generated by Django 4.1.7 on 2023-03-11 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billing_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.CharField(default='BI11M1853903', max_length=100)),
                ('customer_id', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=500)),
                ('created_at', models.CharField(default=None, max_length=500)),
                ('bill_address_line1', models.TextField(default='')),
                ('bill_address_line2', models.TextField(default='')),
                ('bill_country', models.CharField(max_length=500)),
                ('bill_city', models.CharField(max_length=500)),
                ('bill_state', models.CharField(max_length=500)),
                ('bill_pincode', models.CharField(max_length=500)),
                ('shipp_phone', models.CharField(max_length=500)),
                ('shipp_email', models.CharField(max_length=500)),
                ('shipp_address_line1', models.TextField(default='')),
                ('shipp_address_line2', models.TextField(default='')),
                ('shipp_country', models.CharField(max_length=500)),
                ('shipp_city', models.CharField(max_length=500)),
                ('shipp_state', models.CharField(default=None, max_length=500)),
                ('shipp_pincode', models.CharField(default=None, max_length=500)),
                ('product_id', models.CharField(default=None, max_length=500)),
                ('product_price', models.CharField(default=None, max_length=500)),
                ('product_quantity', models.CharField(default=None, max_length=500)),
                ('sub_total_price', models.CharField(default=None, max_length=500)),
                ('shipping_charges', models.CharField(default=None, max_length=500)),
                ('total_price', models.CharField(default=None, max_length=500)),
                ('cart_id', models.CharField(default=None, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(default='CAR11M1853903', max_length=100)),
                ('customer_id', models.CharField(blank=True, default='', max_length=50)),
                ('product_id', models.CharField(blank=True, default='', max_length=50)),
                ('total_price', models.CharField(blank=True, default='', max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.IntegerField()),
                ('user_name', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('date', models.CharField(blank=True, default='11-03-2023 21:18:53', max_length=50)),
            ],
            options={
                'db_table': 'Cart',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(default='CC11M1853903', max_length=100)),
                ('category_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(default='CUS11M1853903', max_length=100)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=500)),
                ('created_at', models.CharField(default=None, max_length=500)),
                ('bill_address_line1', models.TextField(default='')),
                ('bill_address_line2', models.TextField(default='')),
                ('bill_country', models.CharField(default=None, max_length=500)),
                ('bill_city', models.CharField(default=None, max_length=500)),
                ('bill_state', models.CharField(default=None, max_length=500)),
                ('bill_pincode', models.CharField(default=None, max_length=500)),
                ('shipp_phone', models.CharField(default=None, max_length=500)),
                ('shipp_email', models.CharField(default=None, max_length=500)),
                ('shipp_address_line1', models.TextField(default='')),
                ('shipp_address_line2', models.TextField(default='')),
                ('shipp_country', models.CharField(default=None, max_length=500)),
                ('shipp_city', models.CharField(default=None, max_length=500)),
                ('shipp_state', models.CharField(default=None, max_length=500)),
                ('shipp_pincode', models.CharField(default=None, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default='OD11M1853903', max_length=100)),
                ('product_id', models.CharField(blank=True, default='', max_length=50)),
                ('customer_id', models.CharField(blank=True, default='', max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('address', models.CharField(blank=True, default='', max_length=50)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('date', models.CharField(blank=True, default='', max_length=150)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(default='PR11M1853903', max_length=100)),
                ('product_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='uploads/products/')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myntra_store.category')),
            ],
        ),
    ]
