# Generated by Django 4.1.7 on 2023-03-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myntra_store', '0008_customercontactus_alter_billing_details_bill_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe_to_NewsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribtion_id', models.CharField(default='SUB19M4612517', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('customer_id', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=500)),
                ('message', models.CharField(max_length=500)),
                ('created_at', models.CharField(default=None, max_length=500)),
            ],
            options={
                'db_table': 'Subscribe_to_NewsLetter',
            },
        ),
        migrations.AlterField(
            model_name='billing_details',
            name='bill_id',
            field=models.CharField(default='BI19M4612517', max_length=100),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(default='CAR19M4612517', max_length=100),
        ),
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.CharField(blank=True, default='19-03-2023 01:46:12', max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.CharField(default='CC19M4612501', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='CUS19M4612517', max_length=100),
        ),
        migrations.AlterField(
            model_name='customercontactus',
            name='customer_contact_us_id',
            field=models.CharField(default='CON19M4612517', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='OD19M4612517', max_length=100),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='product_id',
            field=models.CharField(default='PR19M4612501', max_length=100),
        ),
    ]
