# Generated by Django 4.1.7 on 2023-03-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myntra_store', '0009_subscribe_to_newsletter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing_details',
            name='product_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='billing_details',
            name='bill_id',
            field=models.CharField(default='BI20M2339105', max_length=100),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(default='CAR20M2339105', max_length=100),
        ),
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.CharField(blank=True, default='20-03-2023 21:23:39', max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.CharField(default='CC20M2339105', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='CUS20M2339105', max_length=100),
        ),
        migrations.AlterField(
            model_name='customercontactus',
            name='customer_contact_us_id',
            field=models.CharField(default='CON20M2339105', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='OD20M2339105', max_length=100),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='product_id',
            field=models.CharField(default='PR20M2339105', max_length=100),
        ),
        migrations.AlterField(
            model_name='subscribe_to_newsletter',
            name='subscribtion_id',
            field=models.CharField(default='SUB20M2339105', max_length=100),
        ),
    ]
